### PR TITLE
Travis CI: OSX support

### PR DESCRIPTION
**Pull request by elijahr**
+ bump version to 1.1.0

### CODE REVIEW

**Comment by elijahr** [comment]
@gabrieldemarmiesse I don't seem to have write access to this repo and I'd like to merge this and release to PyPI. Would you please give me write access?

**Comment by gabrieldemarmiesse** [comment]
It's strange let me check that.

**Comment by gabrieldemarmiesse** [comment]
It seems you didn't accept the invitation yet

**Comment by gabrieldemarmiesse** [comment]
https://github.com/gabrieldemarmiesse/python-autopxd2/invitations

**Comment by elijahr** [comment]
@gabrieldemarmiesse Ah, I didn't check my notifications. Thank you very much.

**Pull request merged**
