### PR TITLE
Support additional compiler directives with -D option

### PR DESCRIPTION
**Pull request by primal100**

### CODE REVIEW

**Comment by elijahr** [comment]
Thank you for the contribution!

**Comment by elijahr** [comment]
@gabrieldemarmiesse looks like I can't merge PRs due to the status checks, and travis CI for open source is no more. Can you make me an admin of this project so I can migrate it to Github Actions?

**Comment by gabrieldemarmiesse** [comment]
It seems I can't make you admin. The button doesn't appear. I think it's because I'm not a paid user. Just ping me when you need something approved or merged (including github actions) and I'll do it quickly :)

**Comment by elijahr** [comment]
@primal100 this has been published on PyPI ([autopxd2 v2.0.1](https://pypi.org/project/autopxd2/2.0.1/)).

**Comment by primal100** [comment]
Awesome thanks a lot. Makes things a lot easier for me!

**Pull request merged**
